services:
    knp_rad_prototype.prototype.method.form.create_form:
        class: Knp\Rad\Prototype\Prototype\Method
        lazy: true
        public: false
        arguments:
            - @form.factory
            - create
        tags:
            - { name: knp_rad_prototype.prototype_method, alias: createForm, domain: form }

    knp_rad_prototype.prototype.method.form.create_builder:
        class: Knp\Rad\Prototype\Prototype\Method
        lazy: true
        public: false
        arguments:
            - @form.factory
            - createBuilder
        tags:
            - { name: knp_rad_prototype.prototype_method, alias: createFormBuilder, domain: form }
