services:
    knp_rad_prototype.prototype.container:
        class: Knp\Rad\Prototype\Prototype\Container

    knp_rad_prototype.event_listener.controller_as_prototype_listener:
        class: Knp\Rad\Prototype\EventListener\ControllerAsPrototypeListener
        arguments:
            - @knp_rad_prototype.prototype.container
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onController }

    knp_rad_prototype.data_collector.prototype_collector:
        class: Knp\Rad\Prototype\DataCollector\PrototypeCollector
        arguments:
            - @knp_rad_prototype.prototype.container
        tags:
            - { name: data_collector, template: "PrototypeBundle::wdt.html.twig", id: "knp_rad_prototype" }
            - { name: kernel.event_listener, event: kernel.controller, method: onController }
